#!/bin/bash

# This script shows how to use arrays. There is one 'trick' where we can change 
# numbering indexes - here index 4'th is ommited.
#
# Usage:
# ./array_primer

array=(one two three four [5]=five)

echo "Array size: ${#array[*]}"

echo "Array items:"
for item in ${array[*]}
do
	printf "	%s\n" $item
done

echo "Array indexes:"
for index in ${!array[*]}
do
	printf "	%d\n" $index
done

echo "Array items and indexes:"
for index in ${!array[*]}
do
	printf "%4d: %s\n" $index ${array[$index]}
done

exit 0
